export default Object.freeze({
  CHAT_LOADER_START: 'CHAT_LOADER_START',
  CHAT_LOADER_FINISH: 'CHAT_LOADER_FINISH',

  CHAT_LOGIN: 'CHAT_LOGIN',
  CHAT_LOGIN_SUCCESS: 'CHAT_LOGIN_SUCCESS',
  CHAT_LOGIN_FAIL: 'CHAT_LOGIN_FAIL',

  CHAT_LOGOUT: 'CHAT_LOGOUT',
});
